### ISSUE TITLE
Is there anyway to fetch secret file that is not on the same repository?

### ISSUE THREAD

**Issue by runlevel5** [envato/ejson2env-buildkite-plugin#4]
I have a scenario in which buildkite infrastructure codes (such as secrets ejson) are placed in an external git repository. I would like to propose that we extend the functionality to fetch remote file via HTTP/HTTPS:

```
steps:
  - name: Tests
    plugins:
      - envato/ejson2env#v0.1.0:
          ejson_file: https://path.to/secrets.ejson
          ejson_private_key_env_key: EJSON_PRIVATE_KEY
```

I am happy to cook up a patch if you are okay with this @stevehodgkiss
